name = "plushie_gleam"
version = "0.4.0"
binary_version = "0.4.0"
target = "erlang"

description = "Native desktop GUI framework for Gleam, powered by iced"
licences = ["MIT"]
repository = { type = "github", user = "plushie-ui", repo = "plushie-gleam" }
links = [
  { title = "Rust binary", href = "https://github.com/plushie-ui/plushie" },
  { title = "Elixir SDK", href = "https://github.com/plushie-ui/plushie-elixir" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.29.0 and < 2.0.0"
gleam_otp = ">= 0.14.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glepack = ">= 0.1.0 and < 1.0.0"
telemetry = ">= 1.0.0 and < 2.0.0"
file_system = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
